services:
  lfs:
    image: ghcr.io/tuatmcc/lfs-server:sha-8ca8421
    container_name: lfs-server
    environment:
      - LFS_ADMINUSER=admin
      - LFS_ADMINPASS=secret
      - LFS_SCHEME=http
      - LFS_LISTEN=http://localhost:8080
    restart: unless-stopped
    ports:
      - 9999:8080

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command:
      - tunnel
      - --no-autoupdate
      - run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped

networks:
  default:
    driver: bridge
