services:
  lfs:
    image: lfs-test-server:latest
    container_name: lfs-server
    environment:
      - LFS_ADMINUSER=admin
      - LFS_ADMINPASS=secret
      - LFS_HOST=0.0.0.0
      - LFS_PORT=8080
    volumes:
      - lfs-data:/data
    ports:
      - "8080:8080"
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    restart: unless-stopped

volumes:
  lfs-data:
