[helpers]

[default]
depends = []

[default.files]
"powershell/profile.ps1" = "Documents/PowerShell/Microsoft.PowerShell_profile.ps1"
"git/.gitconfig" = "~/.gitconfig"
"git/.gitignore_global" = "~/.gitignore_global"

[default.variables]

[settings]
default_target_type = "automatic"
