return {
	{
		"romus204/tree-sitter-manager.nvim",
		event = { "BufReadPost", "BufNewFile" },
		config = function()
			require("tree-sitter-manager").setup({
				auto_install = true,
				ensure_installed = {
					"astro",
					"bash",
					"c",
					"cmake",
					"comment",
					"cpp",
					"css",
					"diff",
					"dockerfile",
					"git_config",
					"gitcommit",
					"gitignore",
					"go",
					"gomod",
					"graphql",
					"html",
					"java",
					"javascript",
					"jsdoc",
					"json",
					"latex",
					"lua",
					"markdown",
					"markdown_inline",
					"python",
					"regex",
					"rust",
					"toml",
					"tsx",
					"typescript",
					"typst",
					"vimdoc",
					"xml",
					"yaml",
				},
				highlight = true,
			})
		end,
	},
}
