# Auto-generated using compose2nix v0.3.3-pre.
{ pkgs, lib, ... }:

{
  # Runtime
  virtualisation.docker = {
    enable = true;
    autoPrune.enable = true;
  };
  virtualisation.oci-containers.backend = "docker";

  # Containers
  virtualisation.oci-containers.containers."cloudflared" = {
    image = "cloudflare/cloudflared:latest";
    environmentFiles = [
      "/etc/docker-env-lfs"
    ];
    cmd = [ "tunnel" "--no-autoupdate" "run" ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=cloudflared"
      "--network=lfs-server_default"
    ];
  };
  systemd.services."docker-cloudflared" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-lfs-server_default.service"
    ];
    requires = [
      "docker-network-lfs-server_default.service"
    ];
    partOf = [
      "docker-compose-lfs-server-root.target"
    ];
    wantedBy = [
      "docker-compose-lfs-server-root.target"
    ];
  };
  virtualisation.oci-containers.containers."lfs-server" = {
    image = "ghcr.io/tuatmcc/lfs-server:sha-8ca8421";
    environmentFiles = [
      "/etc/docker-env-lfs"
    ];
    ports = [
      "9999:8080/tcp"
    ];
    log-driver = "journald";
    extraOptions = [
      "--network-alias=lfs"
      "--network=lfs-server_default"
    ];
  };
  systemd.services."docker-lfs-server" = {
    serviceConfig = {
      Restart = lib.mkOverride 90 "always";
      RestartMaxDelaySec = lib.mkOverride 90 "1m";
      RestartSec = lib.mkOverride 90 "100ms";
      RestartSteps = lib.mkOverride 90 9;
    };
    after = [
      "docker-network-lfs-server_default.service"
    ];
    requires = [
      "docker-network-lfs-server_default.service"
    ];
    partOf = [
      "docker-compose-lfs-server-root.target"
    ];
    wantedBy = [
      "docker-compose-lfs-server-root.target"
    ];
  };

  # Networks
  systemd.services."docker-network-lfs-server_default" = {
    path = [ pkgs.docker ];
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      ExecStop = "docker network rm -f lfs-server_default";
    };
    script = ''
      docker network inspect lfs-server_default || docker network create lfs-server_default --driver=bridge
    '';
    partOf = [ "docker-compose-lfs-server-root.target" ];
    wantedBy = [ "docker-compose-lfs-server-root.target" ];
  };

  # Root service
  # When started, this will automatically create all resources and start
  # the containers. When stopped, this will teardown all resources.
  systemd.targets."docker-compose-lfs-server-root" = {
    unitConfig = {
      Description = "Root target generated by compose2nix.";
    };
    wantedBy = [ "multi-user.target" ];
  };
}
