---
keypress_delay_ms: 20

modmap:
  - name: General
    remap:
      CapsLock:
        held: Ctrl_L
        alone: Esc
        alone_timeout_millis: 500
      Muhenkan:
        held: Alt_R
        alone: Space
        alone_timeout_millis: 500
      Space:
        held: Alt_R
        alone: Space
        alone_timeout_millis: 500
      Henkan:
        held: Alt_R
        alone: Space
        alone_timeout_millis: 500
      Alt_R: Henkan
      Katakana: Henkan
      Hiragana: Henkan

keymap:
  - name: Mac Like General
    application:
      not: [org.wezfurlong.wezterm, kitty]
    remap:
      SUPER-a: Ctrl-a
      SUPER-c: Ctrl-c
      SUPER-x: Ctrl-x
      SUPER-v: Ctrl-v
      SUPER-s: Ctrl-s
      SUPER-f: Ctrl-f
      SUPER-z: Ctrl-z
      SUPER-SHIFT-z: Ctrl-SHIFT-z
      Ctrl-b: left
      Ctrl-F: right
      Ctrl-p: up
      Ctrl-n: down
      Ctrl-a: home
      Ctrl-e: end

  - name: Mac Like Chrome
    application:
      only: [google-chrome]
    remap:
      SUPER-t: Ctrl-t
      SUPER-l: Ctrl-l
      SUPER-w: Ctrl-w
      SUPER-SHIFT-t: Ctrl-SHIFT-t
