---
keypress_delay_ms: 20

modmap:
  - name: General
    remap:
      CapsLock:
        held: Ctrl_L
        alone: Esc
      Muhenkan:
        held: Alt_R
        alone: Space
      Space:
        held: Alt_R
        alone: Space
      Henkan:
        held: Alt_R
        alone: Space
      Alt_R: Henkan
      Katakana: Henkan

keymap:
  - name: Mac Like SUPER
    application:
      not: [org.wezfurlong.wezterm, kitty]
    remap:
      SUPER-c: Ctrl-c
      SUPER-x: Ctrl-x
      SUPER-v: Ctrl-v
      SUPER-s: Ctrl-s
      SUPER-f: Ctrl-f
      SUPER-z: Ctrl-z
      SUPER-SHIFT-z: Ctrl-SHIFT-z
      Ctrl-b: left
      Ctrl-F: right
      Ctrl-p: up
      Ctrl-n: down

  - name: Line Move
    application:
      not: [org.wezfurlong.wezterm, code-url-handler, kitty]
    remap:
      SUPER-a: Ctrl-a
      CONTROL-a: home
      CONTROL-e: end

  - name: Mac Like Chrome
    application:
      only: google-chrome
    remap:
      SUPER-t: Ctrl-t
      SUPER-l: Ctrl-l
      SUPER-w: Ctrl-w
      SUPER-SHIFT-t: Ctrl-SHIFT-t
